server:
  port: 8081

spring:
  datasource:
    username: root
    password: 320382@liuwei
    url:
    driver-class-name:
    type:
    druid:
      max-wait: 60000
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1 FROM DUAL
      time-between-eviction-runs-millis: 300000
      min-evictable-idle-time-millis: 1800000
      min-idle: 10
      max-active: 50
      initial-size: 5

  kafka:
    consumer:
      topic: TEST
      bootstrap-servers:
        -
      group-id:
      auto-offset-reset:
      enable-auto-commit: true
      auto-commit-interval: 1000
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 5
      max-partition-fetch-bytes: 10240000

current:
  threadsize: 6

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml